<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for your message. Our team wi_a6901e</name>
   <tag></tag>
   <elementGuidId>9dee5f93-4c9c-41eb-a4cc-a648156cc574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wpcf7-response-output</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wpcf7-f5-o1']/form/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6751fb8e-7d1d-4c6f-b534-addd0a5ced93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-response-output</value>
      <webElementGuid>62a175ea-7408-419a-b0ac-c4fde32b85c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21d083f1-9339-450e-9f80-4e14bbc98aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your message. Our team will respond you soon.</value>
      <webElementGuid>09f48991-f8a0-41f8-8115-c3eeb6812319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f5-o1&quot;)/form[@class=&quot;wpcf7-form sent&quot;]/div[@class=&quot;wpcf7-response-output&quot;]</value>
      <webElementGuid>82cd5933-6aeb-4d55-bc6a-908c1ec4a1b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f5-o1']/form/div[3]</value>
      <webElementGuid>8bc319e1-3de2-433e-b759-9276db8724cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simply fill the form and our team will contact you soon.'])[1]/following::div[1]</value>
      <webElementGuid>7e42f629-a4f2-49ea-a71f-c3bbe701d307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solve'])[1]/following::div[2]</value>
      <webElementGuid>ce91f95b-dac0-4b06-9d9d-1f49d7f9c659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>058d39be-724c-40a3-b3a0-115d2857252f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thank you for your message. Our team will respond you soon.' or . = 'Thank you for your message. Our team will respond you soon.')]</value>
      <webElementGuid>081b928d-3110-4638-9805-547172484dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
