<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_wpcf7-form-control has-spinne_f93865</name>
   <tag></tag>
   <elementGuidId>490e85b4-2ed4-47d5-981e-cde3c9faaf5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.wpcf7-form-control.has-spinner.wpcf7-submit.red-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Send Message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a491c315-2875-4de6-a4f3-d77f164b4303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ef4d4a9d-d0f6-4e99-a09c-fb7f5ed8db84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send Message</value>
      <webElementGuid>7789715e-1bd2-485e-9b00-299a5809d9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control has-spinner wpcf7-submit red-btn</value>
      <webElementGuid>bd2ca378-6363-4bb7-ae36-30f783b6537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f5-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/p[1]/input[@class=&quot;wpcf7-form-control has-spinner wpcf7-submit red-btn&quot;]</value>
      <webElementGuid>d36ec2a8-8d9f-499b-9a01-cf12683158f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Send Message']</value>
      <webElementGuid>96fe13e8-81e6-4068-94da-c942e21d5a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f5-o1']/form/div[2]/div/p/input</value>
      <webElementGuid>790430a0-f3cf-4a76-a8f2-cd3f9ef30574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>c7b3018d-95eb-4f38-92c2-aae640fed72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>675eaba5-6d42-487e-b713-4dd3f1809148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
