<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_App Development  TestingWebsite Deve_e473fb</name>
   <tag></tag>
   <elementGuidId>28f0e67a-a5f7-4449-a900-5511be4411ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;service&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='service']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18417fa5-feec-4747-bdcd-925636cc99df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service</value>
      <webElementGuid>cc579728-4af1-4865-8310-9f33330ac06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required form-control</value>
      <webElementGuid>7b19cfbb-280b-4017-96a8-1e1fcde72a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5207dcbb-e3d0-4396-a987-347adfa3e7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6080900b-dafd-4bed-8147-f1dcdcee2007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>App Development &amp; TestingWebsite Development &amp; DesignCustom Software DevelopmentUX &amp; UI DesignOther</value>
      <webElementGuid>93f7956e-c516-451d-b819-cfbb2157466c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f5-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/span[@class=&quot;wpcf7-form-control-wrap service&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required form-control&quot;]</value>
      <webElementGuid>f3a82162-408e-460b-8b5f-4b00a72777c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='service']</value>
      <webElementGuid>155d3a97-ba6f-4a04-8298-bb20f40a3a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f5-o1']/form/div[2]/div/div[3]/span/select</value>
      <webElementGuid>ace7f553-c916-4801-b0dd-555f90010f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::select[1]</value>
      <webElementGuid>a8607c4d-5982-4d91-bf7d-81f93ecc1a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[1]/following::select[1]</value>
      <webElementGuid>f347bf49-b17b-4411-a87b-9df458d4e994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solve'])[1]/preceding::select[1]</value>
      <webElementGuid>b3026ba9-9578-428e-a30c-0e289061279d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ed088868-482c-4ac8-8922-d62b81ca7566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'service' and (text() = 'App Development &amp; TestingWebsite Development &amp; DesignCustom Software DevelopmentUX &amp; UI DesignOther' or . = 'App Development &amp; TestingWebsite Development &amp; DesignCustom Software DevelopmentUX &amp; UI DesignOther')]</value>
      <webElementGuid>780846bb-8164-4a35-b545-1a2c60e8bebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
